name: httpserver
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides: 
  shelf_router: #1.1.4
    git: 
      url: git@github.com:shirne/shelf.git
      ref: 86aec19482ae5c11f03813a7aac40e28203cd9eb
      path: pkgs/shelf_router

dependencies:
  args: ^2.4.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  shelf_static: 1.1.2
  shelf_web_socket: 1.0.4
  mysql_client: 0.0.27
  ini: ^2.1.0
  logging: 

dev_dependencies:
  http: ^0.13.6
  lints:
  test:
  shelf_router_generator: #^1.0.6
    git:
      url: git@github.com:shirne/shelf.git
      ref: 86aec19482ae5c11f03813a7aac40e28203cd9eb
      path: pkgs/shelf_router_generator
  build_runner:
